config/routes.rb
Rails.application.routes.draw do
  
  

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get 'games/memory', to: 'games#memory', as: :memory
  get 'games/testing', to: 'games#testing', as: :testing
  get 'games/blackjack', to: 'games#blackjack', as: :blackjack
  get 'games/stopwatch', to: 'games#stopwatch', as: :stopwatch
  get 'games/spaceship', to: 'games#spaceship', as: :spaceship
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :memories,            only: [:create, :index]
  resources :blackjacks,          only: [:create, :index, :update]
  resources :spaceships,          only: [:create, :index]
  resources :stopwatches,         only: [:create, :index]
  
  

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    def index
    end
    def testing
    end
    def memory
    end
    def blackjack
        if logged_in? && current_user.blackjack.nil?
            current_user.create_blackjack(score:500)
        end
    end
    def stopwatch
    end
    def spaceship
    end
    
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_greeting.html.erb
<div class="greeting">
    <h4 id="greeting">Hi <span id="name"></span>, welcome to the game!</h4>
    <% if !logged_in? %>
        <p id="logged" display="none"><em>To make your score recorded, please <a href="/login">log in</a> or <a href="/signup">sign up</a></em></p>
    <% end %>
    <%= javascript_tag do %>
        $("body").attr("data-no-turbolink", "");
        <% if logged_in? %>
            var logged_in = true;
            $("#name").html("<%= current_user.name %>");
        <% else %>
            var logged_in = false;
            $("#name").html("there");
            <!--$("#logged").removeAttr("display");-->
            <!--var login = "<a href="/login">log in</a>";-->
            <!--var signup = "<a href="/signup">sign up</a>";-->
            
            <!--$(".greeting").append("<br></em>");-->
            
        <% end %>
    <% end %>
</div>

app/views/games/blackjack.html.erb
<% provide(:title, 'Blackjack') %>
<%= javascript_include_tag 'blackjack' %> 
<h1>Blackjack</h1>
<div id="game">
<%= render 'greeting' %>
<%= javascript_tag do %>
	<% if logged_in? %>
		var bank = <%= current_user.blackjack.score %>;
		var blackjack_id = <%= current_user.blackjack.id %>;
	<% else %>
		var bank = 500;
	<% end %>
<% end %>

	<canvas id="canvas" class="img-rounded" width="600" height="500" style="border: 1px solid black" background-color="green"></canvas>
	<br>
	
	<button id="btn_deal" class="btn btn-info">Deal</button>
	<button id="btn_hit" class="btn btn-success">Hit</button>
	<button id="btn_stand" class="btn btn-danger">Stand</button>
	<button id="btn_reset" class="btn btn-warning">Reset Bank</button>
	<div class="row">
		<div>
			<p>Set Bet ($10 ~ $500): <span id="bet_value">10</span></p>
			<div class="col-md-2 col-md-offset-5">
				<input type="range" min="10" max="500" value="10" step="10" onchange="set_bet(this.value)"/>
			</div>
		</div>
	</div>
	<%= link_to 'Show all records', blackjacks_path %>
</div>

app/views/games/memory.html.erb
<% provide(:title, "Memory") %>
<%= javascript_include_tag 'memory' %> 
<h1>Memory Game</h1>
<div id="game">
	<%= render 'greeting' %>
	<p>There are 10 pairs of cards with 10 different numbers, 
			try to match all pairs as fast as you can!</p>
	<h3 id="time">0:00:0</h3>
	<canvas id="canvas" class="img-rounded" width="250" height="400" style="border:1px solid black"></canvas><br><br>
	
	<button id="btn_start" class="btn btn-primary">start</button>
	<button id="btn_reset" class="btn btn-primary">reset</button>
	<br><%= link_to 'Show all records', memories_path %>
</div>

	
	
	

app/views/games/spaceship.html.erb
<% provide(:title, "Space Ship") %>
<%= javascript_include_tag 'spaceship' %> 
<h1>Space Ship</h1>

<div id="game">
	<%= render 'greeting' %>
	<p><strong>!!! To gain best gaming experience for this game, please use <a href="http://www.google.com/chrome" target="_blank">Google Chrome</a> !!!</strong></p>
	<canvas id="canvas" class="img-rounded" width="800" height="500" style="border: 1px solid black" tabindex="1"></canvas>
	<br>
	<%= link_to 'Show all records', spaceships_path %>
	<p>All the art assets of this game are created by Kim Lathrop</p>
</div>

app/views/games/stopwatch.html.erb
<% provide(:title, "Stopwatch") %>
<%= javascript_include_tag "stopwatch" %>
<h1>Stop Watch</h1>
<div id="game">
	<%= render 'greeting' %>
	<p>Try to stop the watch so that the number of seconds is a whole number!</p>
	<canvas id="canvas" class="img-rounded" width="410" height="250" style="background-color:black"></canvas>
<div id="ctrl_panel">
	<button id="btn_start" class="btn btn-success">start</button>
	<button id="btn_stop" class="btn btn-danger">stop</button>
	<button id="btn_reset" class="btn btn-warning">reset</button>
	<button id="btn_save" class="btn btn-primary">save</button>
</div>
<%= link_to "Show all records", stopwatches_path %>
</div>

app/views/games/testing.html.erb
<% provide(:title, "Game_test") %>
<%= javascript_include_tag 'testing' %> 
<p>Image to use:</p>
<img src="/assets/double_ship.png" alt="The Scream">

<p>Canvas:</p>
<canvas id="myCanvas" width="240" height="297" style="border:1px solid #d3d3d3;">
Your browser does not support the HTML5 canvas tag.
</canvas>